create table app_user (
                          id bigint generated by default as identity primary key,
                          email varchar(255) not null unique,
                          password_hash varchar(255) not null,
                          roles varchar(255) not null
);

create table refresh_token (
                               id bigint generated by default as identity primary key,
                               user_id bigint not null,
                               token_hash varchar(255) not null unique,
                               expires_at timestamp not null,
                               revoked boolean not null default false,
                               created_at timestamp not null default current_timestamp,
                               constraint fk_refresh_token_user foreign key (user_id) references app_user(id) on delete cascade
);

create index idx_refresh_token_user on refresh_token(user_id);